# Generated by Django 2.0.2 on 2018-03-14 08:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('cargo_tracking_code', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.TextField(blank=True, default='')),
                ('sent', models.BooleanField(default=False)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('received', models.BooleanField(default=False)),
                ('received_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_paid', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='TRY', max_length=10, null=True)),
                ('success', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_token', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('card_user_key', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('period_tr', models.CharField(blank=True, default='ay', max_length=5, null=True)),
                ('period_en', models.CharField(blank=True, default='mo', max_length=5, null=True)),
                ('period_months', models.IntegerField(blank=True, default=1, null=True)),
                ('price_tl', models.FloatField(default=24.9)),
                ('price_usd', models.FloatField(blank=True, null=True)),
                ('price_euro', models.FloatField(blank=True, null=True)),
                ('deposit_tl', models.FloatField(default=30)),
                ('deposit_usd', models.FloatField(blank=True, null=True)),
                ('deposit_euro', models.FloatField(blank=True, null=True)),
                ('number_of_books', models.IntegerField(default=4)),
                ('photo_tr', models.ImageField(upload_to='')),
                ('photo_en', models.ImageField(upload_to='')),
                ('info_tr', models.TextField(default='')),
                ('info_en', models.TextField(default='')),
                ('shipment', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourshelf.SubscriptionType'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourshelf.Subscription'),
        ),
        migrations.AddField(
            model_name='bookpackage',
            name='books',
            field=models.ManyToManyField(to='yourshelf.BookSelection'),
        ),
        migrations.AddField(
            model_name='bookpackage',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourshelf.Subscription'),
        ),
    ]
